# Generated by Django 6.0.3 on 2026-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
